# Generated by Django 4.1.5 on 2023-01-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_address_receiver_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='receiver_name',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='receiver_phone_number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
